"""initial schema

Revision ID: 0f3a7f8034b1
Revises: 
Create Date: 2026-04-09 23:50:26.167784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3a7f8034b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemeinden',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('land', sa.String(length=2), nullable=False),
    sa.Column('landkreis', sa.String(length=255), nullable=True),
    sa.Column('ags_code', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('bauamt_name', sa.String(length=255), nullable=True),
    sa.Column('bauamt_email', sa.String(length=255), nullable=True),
    sa.Column('bauamt_phone', sa.String(length=100), nullable=True),
    sa.Column('bauamt_address', sa.String(length=500), nullable=True),
    sa.Column('bauamt_url', sa.String(length=500), nullable=True),
    sa.Column('bauordnung_url', sa.String(length=500), nullable=True),
    sa.Column('bauleitplan_portal_url', sa.String(length=500), nullable=True),
    sa.Column('data_updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gemeinden', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gemeinden_ags_code'), ['ags_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gemeinden_name'), ['name'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_form', sa.String(length=100), nullable=True),
    sa.Column('vat_id', sa.String(length=50), nullable=True),
    sa.Column('handelsreg_nr', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('verified_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verifiedstatus'), nullable=False),
    sa.Column('vat_verified', sa.Boolean(), nullable=True),
    sa.Column('vat_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('BASIC', 'PREMIUM', name='providerplan'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vat_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('preferred_lang', sa.String(length=2), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'EXPERT', name='subscriptionplan'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bebauungsplan_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gemeinde_id', sa.String(length=36), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('plan_number', sa.String(length=100), nullable=True),
    sa.Column('zone_type', sa.Enum('WA', 'WR', 'WB', 'MI', 'MU', 'MD', 'GE', 'GI', 'SO', 'FK', 'PARAGRAPH_34', 'PARAGRAPH_35', name='zonetype'), nullable=False),
    sa.Column('grz_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gfz_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_geschosse', sa.SmallInteger(), nullable=True),
    sa.Column('max_hoehe_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bauweise', sa.String(length=50), nullable=True),
    sa.Column('sonderregeln', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gemeinde_id'], ['gemeinden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bebauungsplan_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bebauungsplan_zones_gemeinde_id'), ['gemeinde_id'], unique=False)

    op.create_table('provider_licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('license_type', sa.Enum('MEISTERBRIEF', 'KAMMERMITGLIED', 'KFW_EXPERTE', 'GUTACHTER_OBUV', 'NOTARZULASSUNG', 'HAFTPFLICHT', 'GEWERBEANMELDUNG', 'BAULEITER_ZULASSUNG', name='licensetype'), nullable=False),
    sa.Column('issuing_body', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('doc_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_licenses_provider_id'), ['provider_id'], unique=False)

    op.create_table('provider_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('BAUFIRMA', 'HANDWERK_ELEKTRO', 'HANDWERK_SANITAER', 'HANDWERK_DACHDECKER', 'HANDWERK_MALER', 'HANDWERK_FLIESENLEGER', 'HANDWERK_BODENLEGER', 'ARCHITEKT', 'STATIKER', 'ENERGIEBERATER', 'GUTACHTER', 'NOTAR', 'MAKLER', 'TRANSPORT', 'KUECHE_MOEBEL', 'GARTENBAUER', 'PV_SOLAR', 'HEIZUNG', 'SMARTHOME', 'VERSICHERUNG', 'UMZUG', 'SONSTIGES', name='providercategory'), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('relevant_stages', sa.JSON(), nullable=True),
    sa.Column('price_range_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_range_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('service_area_plz', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_services_provider_id'), ['provider_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'EXPERT', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'PAST_DUE', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('stripe_sub_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_sub_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gemeinde_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.Enum('NEUBAU_EFH', 'NEUBAU_MFH', 'UMBAU', 'ANBAU', 'KAUF', name='projecttype'), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('address_plz', sa.String(length=10), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_stage', sa.Enum('LAND_SEARCH', 'LAND_CHECK', 'FINANCING', 'LAND_PURCHASE', 'ARCHITECT_SELECT', 'DESIGN_PLANNING', 'BUILDING_PERMIT', 'TENDERING', 'EARTHWORKS', 'FOUNDATION', 'WALLS_CEILINGS', 'ROOF', 'WINDOWS_DOORS_RAW', 'ELECTRICAL', 'PLUMBING', 'FLOORING', 'TILING', 'PLASTERING', 'BUILT_IN_FURNITURE', 'LIGHTING', 'DOORS_STAIRS', 'FACADE_INSULATION', 'GARAGE', 'GARDEN', 'DRIVEWAY', 'FENCING', 'HEATING', 'SOLAR_PV', 'VENTILATION', 'ENERGY_CERTIFICATE', 'SMART_HOME', 'FINAL_ACCEPTANCE', 'OFFICIAL_NOTICES', 'MOVE_IN', 'WARRANTY_TRACKING', name='stagekey'), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('wohnflaeche_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('grundstueck_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gemeinde_id'], ['gemeinden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['bebauungsplan_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_gemeinde_id'), ['gemeinde_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('ai_actions_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('ZONE_LOOKUP', 'DRAFT_LETTER', 'KFW_CALC', 'PROVIDER_SEARCH', 'DOCUMENT_GENERATE', 'TILGUNGSPLAN', 'CHECKLIST_GENERATE', 'DEADLINE_SET', 'REVIEW_ANALYZE', 'GENERAL_CONSULT', name='actiontype'), nullable=False),
    sa.Column('mode', sa.Enum('AUTONOMOUS', 'CONFIRMATION_REQUIRED', 'HUMAN_REQUIRED', name='actionmode'), nullable=False),
    sa.Column('stage_key', sa.Enum('LAND_SEARCH', 'LAND_CHECK', 'FINANCING', 'LAND_PURCHASE', 'ARCHITECT_SELECT', 'DESIGN_PLANNING', 'BUILDING_PERMIT', 'TENDERING', 'EARTHWORKS', 'FOUNDATION', 'WALLS_CEILINGS', 'ROOF', 'WINDOWS_DOORS_RAW', 'ELECTRICAL', 'PLUMBING', 'FLOORING', 'TILING', 'PLASTERING', 'BUILT_IN_FURNITURE', 'LIGHTING', 'DOORS_STAIRS', 'FACADE_INSULATION', 'GARAGE', 'GARDEN', 'DRIVEWAY', 'FENCING', 'HEATING', 'SOLAR_PV', 'VENTILATION', 'ENERGY_CERTIFICATE', 'SMART_HOME', 'FINAL_ACCEPTANCE', 'OFFICIAL_NOTICES', 'MOVE_IN', 'WARRANTY_TRACKING', name='stagekey'), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('full_response', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_actions_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_actions_log_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_actions_log_user_id'), ['user_id'], unique=False)

    op.create_table('financing_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('eigenkapital', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kfw_program', sa.String(length=100), nullable=True),
    sa.Column('kfw_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kfw_zinssatz', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('kfw_laufzeit_years', sa.SmallInteger(), nullable=True),
    sa.Column('kfw_application_date', sa.Date(), nullable=True),
    sa.Column('kfw_status', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bank_zinssatz', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('bank_sollzinsbindung_years', sa.SmallInteger(), nullable=True),
    sa.Column('bank_tilgung_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('laufzeit_years', sa.SmallInteger(), nullable=True),
    sa.Column('landesfoerderung_program', sa.String(length=255), nullable=True),
    sa.Column('landesfoerderung_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'KFW_APPLIED', 'BANK_APPLIED', 'APPROVED', 'ACTIVE', name='financingstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financing_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financing_plans_project_id'), ['project_id'], unique=True)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('stage_key', sa.Enum('LAND_SEARCH', 'LAND_CHECK', 'FINANCING', 'LAND_PURCHASE', 'ARCHITECT_SELECT', 'DESIGN_PLANNING', 'BUILDING_PERMIT', 'TENDERING', 'EARTHWORKS', 'FOUNDATION', 'WALLS_CEILINGS', 'ROOF', 'WINDOWS_DOORS_RAW', 'ELECTRICAL', 'PLUMBING', 'FLOORING', 'TILING', 'PLASTERING', 'BUILT_IN_FURNITURE', 'LIGHTING', 'DOORS_STAIRS', 'FACADE_INSULATION', 'GARAGE', 'GARDEN', 'DRIVEWAY', 'FENCING', 'HEATING', 'SOLAR_PV', 'VENTILATION', 'ENERGY_CERTIFICATE', 'SMART_HOME', 'FINAL_ACCEPTANCE', 'OFFICIAL_NOTICES', 'MOVE_IN', 'WARRANTY_TRACKING', name='stagekey'), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'VIEWED', 'CONTACTED', 'WON', 'LOST', name='leadstatus'), nullable=False),
    sa.Column('price_charged', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    op.create_table('project_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_key', sa.Enum('LAND_SEARCH', 'LAND_CHECK', 'FINANCING', 'LAND_PURCHASE', 'ARCHITECT_SELECT', 'DESIGN_PLANNING', 'BUILDING_PERMIT', 'TENDERING', 'EARTHWORKS', 'FOUNDATION', 'WALLS_CEILINGS', 'ROOF', 'WINDOWS_DOORS_RAW', 'ELECTRICAL', 'PLUMBING', 'FLOORING', 'TILING', 'PLASTERING', 'BUILT_IN_FURNITURE', 'LIGHTING', 'DOORS_STAIRS', 'FACADE_INSULATION', 'GARAGE', 'GARDEN', 'DRIVEWAY', 'FENCING', 'HEATING', 'SOLAR_PV', 'VENTILATION', 'ENERGY_CERTIFICATE', 'SMART_HOME', 'FINAL_ACCEPTANCE', 'OFFICIAL_NOTICES', 'MOVE_IN', 'WARRANTY_TRACKING', name='stagekey'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', 'DONE', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stages_project_id'), ['project_id'], unique=False)

    op.create_table('provider_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ai_anomaly_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verified_deal', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_reviews_provider_id'), ['provider_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('doc_type', sa.Enum('LAGEPLAN', 'BAUZEICHNUNG', 'STATIK', 'KFW_ANTRAG', 'BRIEF', 'GENEHMIGUNG', 'VERTRAG', 'PROTOKOLL', 'ENERGIEAUSWEIS', 'VERSICHERUNG', 'RECHNUNG', 'SONSTIGES', name='doctype'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_draft_content', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['project_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_stage_id'), ['stage_id'], unique=False)

    op.create_table('messages_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_type', sa.Enum('BAUAMT', 'KFW', 'BANK', 'NOTAR', 'PROVIDER', 'VERSICHERUNG', 'OTHER', name='recipienttype'), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_draft', sa.Text(), nullable=False),
    sa.Column('attached_doc_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AWAITING_APPROVAL', 'APPROVED', 'SENT', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['project_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_outbox_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_outbox_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_outbox_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_outbox_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_outbox_stage_id'))
        batch_op.drop_index(batch_op.f('ix_messages_outbox_project_id'))

    op.drop_table('messages_outbox')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_stage_id'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))

    op.drop_table('documents')
    with op.batch_alter_table('provider_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_reviews_provider_id'))

    op.drop_table('provider_reviews')
    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stages_project_id'))

    op.drop_table('project_stages')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_provider_id'))
        batch_op.drop_index(batch_op.f('ix_leads_project_id'))

    op.drop_table('leads')
    with op.batch_alter_table('financing_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financing_plans_project_id'))

    op.drop_table('financing_plans')
    with op.batch_alter_table('ai_actions_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_actions_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_actions_log_project_id'))

    op.drop_table('ai_actions_log')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_gemeinde_id'))

    op.drop_table('projects')
    op.drop_table('subscriptions')
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_services_provider_id'))

    op.drop_table('provider_services')
    with op.batch_alter_table('provider_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_licenses_provider_id'))

    op.drop_table('provider_licenses')
    with op.batch_alter_table('bebauungsplan_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bebauungsplan_zones_gemeinde_id'))

    op.drop_table('bebauungsplan_zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('providers')
    with op.batch_alter_table('gemeinden', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gemeinden_name'))
        batch_op.drop_index(batch_op.f('ix_gemeinden_ags_code'))

    op.drop_table('gemeinden')
    # ### end Alembic commands ###
