"""add notifications cameras

Revision ID: 3577e3f5d63a
Revises: 5b3613ed358f
Create Date: 2026-04-10 21:31:02.937468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3577e3f5d63a'
down_revision = '5b3613ed358f'
branch_labels = None
depends_on = None


def upgrade():
    # Drop types from any previous failed run so op.create_table can recreate them
    op.execute("DROP TYPE IF EXISTS camerafeedtype CASCADE")
    op.execute("DROP TYPE IF EXISTS notificationtype CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_feeds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_type', sa.Enum('RTSP', 'TELEGRAM', name='camerafeedtype'), nullable=False),
    sa.Column('rtsp_url', sa.String(length=512), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('last_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_feeds_project_id'), ['project_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('STAGE_CHANGE', 'LAW_UPDATE', 'FINANCE_ALERT', 'DOCUMENT_MISSING', 'CAMERA_REPORT', 'DEADLINE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('camera_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('stage_key', postgresql.ENUM(name='stagekey', create_type=False), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_progress_pct', sa.SmallInteger(), nullable=True),
    sa.Column('ai_issues', sa.Text(), nullable=True),
    sa.Column('ai_raw_json', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_feeds.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_snapshots_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_snapshots_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_camera_snapshots_captured_at'))
        batch_op.drop_index(batch_op.f('ix_camera_snapshots_camera_id'))

    op.drop_table('camera_snapshots')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('camera_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_feeds_project_id'))

    op.drop_table('camera_feeds')
    # ### end Alembic commands ###
