"""add law_sources and law_update_logs tables

Revision ID: 5b3613ed358f
Revises: df990ff5a085
Create Date: 2026-04-10 18:31:46.047962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3613ed358f'
down_revision = 'df990ff5a085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('check_interval_days', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('law_update_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('affected_stages', sa.JSON(), nullable=True),
    sa.Column('suggested_update', sa.Text(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['law_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('law_update_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_law_update_logs_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_law_update_logs_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_update_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_law_update_logs_source_id'))
        batch_op.drop_index(batch_op.f('ix_law_update_logs_checked_at'))

    op.drop_table('law_update_logs')
    op.drop_table('law_sources')
    # ### end Alembic commands ###
