"""add_parcels_table

Revision ID: 8d6c7ffb88fa
Revises: ec9224084584
Create Date: 2026-04-11 16:03:46.050132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d6c7ffb88fa'
down_revision = 'ec9224084584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gemeinde_id', sa.String(length=36), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('gemarkung', sa.String(length=255), nullable=True),
    sa.Column('flurstueck_nr', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('parcel_type', sa.Enum('KAUF', 'MIETE', 'ERBBAURECHT', 'GEMEINDE', name='parceltype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESERVED', 'SOLD', 'INACTIVE', name='parcelstatus'), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_eur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_type', sa.String(length=100), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('contact_website', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gemeinde_id'], ['gemeinden.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcels_gemeinde_id'), ['gemeinde_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_provider_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_gemeinde_id'))

    op.drop_table('parcels')
    # ### end Alembic commands ###
