"""provider_portal_fields

Revision ID: 95a48b7fe800
Revises: 0f3a7f8034b1
Create Date: 2026-04-10 14:45:15.023606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a48b7fe800'
down_revision = '0f3a7f8034b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portal_active', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('chatbot_enabled', sa.Boolean(), nullable=True, server_default='true'))
        batch_op.add_column(sa.Column('chatbot_greeting', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('chatbot_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('available_slots', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('available_slots')
        batch_op.drop_column('chatbot_prompt')
        batch_op.drop_column('chatbot_greeting')
        batch_op.drop_column('chatbot_enabled')
        batch_op.drop_column('hero_image_path')
        batch_op.drop_column('tagline')
        batch_op.drop_column('portal_active')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
