"""add project_mailboxes table

Revision ID: df990ff5a085
Revises: 95a48b7fe800
Create Date: 2026-04-10 17:38:22.994986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df990ff5a085'
down_revision = '95a48b7fe800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_mailboxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_address', sa.String(length=255), nullable=False),
    sa.Column('app_password_enc', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_mailboxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_mailboxes_project_id'), ['project_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_mailboxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_mailboxes_project_id'))

    op.drop_table('project_mailboxes')
    # ### end Alembic commands ###
